# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 92ccc293308553f2f39dad47accd15158e48355afed1ba934026d12563ed60f46258fed1e5527ac7635af55a5cf7efdcc2fa7d2ac05d3d46a34ec9a9e166fdf7

test:
  secret_key_base: de3a8a18de8ae67046f56f5677bba178e0bf17eca6f5c96afd3e66b015d0a7bdcb4e38531245c40af02aec069c8a5abc1fc5026bba57179964d87457d0025eb7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
